name: create draft release

on:
  pull_request:
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'draft-release')
    name: Create Tag and Draft Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Calculate Tag and release names
      run: |
        t=$(echo ${{ github.event.pull_request.title }} | sed -ne 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
        if [ -z "$t" ]; then
        echo Malformed title for PR; failed to extract semVer tag
        return 1
        fi
        echo ::set-env name=TAG_NAME::"v${t}"
        echo ::set-env name=RELEASE_NAME::"v${t} Release"
    - name: Create and push Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a ${{ env.TAG_NAME }} -m "${{ env.RELEASE_NAME }}"
        git push origin ${{ env.TAG_NAME }}
